### ISSUE TITLE
no matches for kind "TCPMapping" in version "ambassador/v1"

### ISSUE THREAD

**Issue by kfkawalec** [datawire/ambassador#1444]
I deployed ambassador from turtorial and standard route works, but when I try to add TCPMapping I see error:
no matches for kind "TCPMapping" in version "ambassador/v1"

**Versions:**
 - Ambassador: 0.53.1
 - Kubernetes: bare metal, host network, 1.12.5

**Comment by kfkawalec** [comment]
I found solution.

**Comment by zamanianb** [comment]
@kfkawalec 
Would you please elaborate what was the solution?
We have experienced the same problem

**Comment by kfkawalec** [comment]
I only test ambassador and don't remember details, but this was my mistake.
Problem was related to ambassador installation, I don't have kubernetes TCP Mapping object.
But as I say I dont remember details.

**Comment by psalaberria002** [comment]
When using CRDs the apiVersion is `getambassador.io/v1` instead of `ambassador/v1`.

**Comment by zamanianb** [comment]
Thank you, your answer is accurate
I just would like to mention that initially we misunderstood the ambassador documentation about Mapping examples here
https://www.getambassador.io/reference/mappings/#additional-example-mappings
Because, when it mentions about 
```
---
apiVersion: ambassador/v1
kind:  Mapping
name:  backend-https_mapping
prefix: /backend/secure/
rewrite: /secure/
service: https://tour
```
It was not obvious in documentation that it is talking about mapping configuration as ```annotation``` and not mapping configuration as ```CRD```. So we thought it is an CRD and were applying it as yaml file and were getting the error stated earlier. 

I think many other people were ran into same scenario as the original user who opened this issue

Thanks

**Comment by 759803573** [comment]
helm version(v2.9.1) don't automatic installation crds.
upgrade to new version(v2.16.0) to fix it.
