### ISSUE TITLE
Docs say the empty string is the default for Mapping.rewrite but that's not true

### ISSUE THREAD

**Issue by aeb-sia** [datawire/ambassador#2059]
**Describe the bug**
If you create a Mapping and set rewrite to the empty string, it doesn't actually strip the prefix as the documentation says.

**Versions:**
 - Ambassador: 0.85.0

**Comment by aeb-sia** [comment]
AFAIK this hasn't changed in a new release, has it?

**Comment by richarddli** [comment]
We just revamped the docs -- a PR with suggested fix would be appreciated!

**Comment by aeb-sia** [comment]
We switched back to nginx due to a couple of issues we had with ambassador/envoy

**Comment by richarddli** [comment]
Thanks for the feedback! Any other specific issues?

**Comment by aeb-sia** [comment]
* https://github.com/envoyproxy/envoy/issues/9129
* https://github.com/datawire/ambassador/issues/2010

**Comment by aeb-sia** [comment]
Other than that we were actually pretty happy with ambassador. Issues becoming constantly stale without anyone looking at them wasn't very nice.

In the end we decided to move back to nginx because we know it more than ambassador. If we had decided to stick with ambassador one of our team would've had to get pretty deep into envoy/ambassador to start understanding and debugging. We decided that wasn't worth it

**Comment by richarddli** [comment]
Thanks for the feedback! Yes, working on trying to be more responsive to issues in general. A lot of the issues (#2148 is an example) are issues where we can't necessarily reproduce them easily because of some specific cluster/Ambassador config. Not that this is a good excuse, but this is what is happening.

We are revamping our docs, and constantly expanding our automated test coverage (e.g., we now run automated perf tests that measure p95 latency under load), all of which help.
