### ISSUE TITLE
redeploying a kubernetes service results in temporary outage

### ISSUE THREAD

**Issue by rhs** [datawire/ambassador#22]
when I redeploy a kubernetes service sitting behind a given ambassador route, there seem to be 5-10 seconds of downtime... this doesn't happen if I'm connecting directly to the external ip of the service

**Comment by kflynn** [comment]
The issue seems to be that, since Envoy only queries the SDS every 15 seconds by default, it can have an endpoint that's stale if the endpoint goes away right after the query (as can happen when the service is updated).

The simplest way to work around this for Ambassador-as-a-service-mesh is likely just to let Kubernetes handle load balancing for the moment. That costs a lot of features, but it's dirt simple.

Other things we could do:

- drop the 15-second poll to 1 second
- document that you must do rolling upgrades to avoid the outage (ugh)
- teach Envoy how to accept updates over a websocket asynchronously ( ;) and also ugh)

**Comment by kflynn** [comment]
Closing since we switched away from SDS for launch. Also see #47.
