### ISSUE TITLE
https on minikube is broken

### ISSUE THREAD

**Issue by daninthewoods** [datawire/ambassador#2215]
**Describe the bug**
Bad https endpoint, SSL error on fresh install of AES 1.0.0 on Minikube.  Verbose curl results in:
```
curl -v https://192.168.64.5:30845
* Rebuilt URL to: https://192.168.64.5:30845/
*   Trying 192.168.64.5...
* TCP_NODELAY set
* Connected to 192.168.64.5 (192.168.64.5) port 30845 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
* stopped the pause stream!
* Closing connection 0
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
```
**To Reproduce**

1. Steps to reproduce the behavior:
2. Fresh minikube install
3. Install latest AES 1.0 (1/17/20) from docs using the 4-line install script
4. Verify you can reach the Ambassador splashscreen at http://192.168.64.3:32534/
5. Click the link on the page for console (url of link: https://192.168.64.5:30845/edge_stack/admin)
6. See ERR_SSL_PROTOCOL_ERROR in Chrome.

**Expected behavior**
https endpoint presents a warning page in Chrome that allows you to ignore the cert issue as per the docs.

**Versions (please complete the following information):**

- Image:          quay.io/datawire/aes:1.0.0
- Image ID:       docker-pullable://quay.io/datawire/aes@sha256:4a6577ca83178fbbfd8295d68312b2d92b6820dfd97e6a36e2ec1337ac4cf66b
- minikube version: v1.6.2

**Additional context**

**Comment by daninthewoods** [comment]
[sanitized.zip](https://github.com/datawire/ambassador/files/4082857/sanitized.zip)

**Comment by kflynn** [comment]
Hmmmm, I"m a bit confused here. Your `Host` CR explicitly says to _not_ do TLS -- are you trying to use TLS, or cleartext? :slightly_smiling_face:

**Comment by daninthewoods** [comment]
I'm sorry I used the same upload for both tickets.  You can ignore this sanitized.zip for this ticket as the base AES install has broken TLS on minikube (where I test) and others on slack have validated this is an issue also.

**Comment by devstein** [comment]
@daninthewoods @kflynn  Any solution? I'm facing the same issue

**Comment by alechp** [comment]
Is this what others are seeing?

![Screen Shot 2020-02-07 at 3 21 02 PM](https://user-images.githubusercontent.com/3058939/74073025-a9860280-49bd-11ea-914b-e6418dff95a4.png)

![Screen Shot 2020-02-07 at 3 21 26 PM](https://user-images.githubusercontent.com/3058939/74073030-adb22000-49bd-11ea-90a6-79c316a05a6e.png)

![Screen Shot 2020-02-07 at 3 22 00 PM](https://user-images.githubusercontent.com/3058939/74073044-b3a80100-49bd-11ea-9a0b-24fd8b17ba04.png)

**Comment by jimmya** [comment]
@alechp yes. I ran into exactly the same issue when running ambassador through minikube.

**Comment by alechp** [comment]
@devstein @jimmya 

Found a workaround that fixed it for me. 
### Run these commands
**First**
```
sudo ip route add $(cat ~/.minikube/profiles/minikube/config.json | jq -r ".KubernetesConfig.ServiceCIDR") via $(minikube ip)
```

If that fails, it might be because you need the ip or jq binaries, which can be installed like this:
```
brew install iproute2mac
brew install jq
```

**Second**
```
kubectl run minikube-lb-patch --replicas=1 --image=elsonrodriguez/minikube-lb-patch:0.1 --namespace=kube-system
```

### Result
> notice the external IP is now available (previously would've said "pending" indefinitely because minikube doesn't support load balancers)

![Uploading Screen Shot 2020-02-19 at 2.22.28 PM.png…]()


### Testing it
<img width="952" alt="Screen Shot 2020-02-19 at 2 23 23 PM" src="https://user-images.githubusercontent.com/3058939/74882498-15ecf400-5324-11ea-98a7-6956d5eec5fa.png">
<img width="952" alt="Screen Shot 2020-02-19 at 2 23 26 PM" src="https://user-images.githubusercontent.com/3058939/74882501-171e2100-5324-11ea-91f7-af18dd33298d.png">
<img width="952" alt="Screen Shot 2020-02-19 at 2 23 32 PM" src="https://user-images.githubusercontent.com/3058939/74882502-171e2100-5324-11ea-8aac-0b4481750874.png">

Seems like the "proceed to unsafe" option is only available when accessed through the LoadBalancer url -- not the minikube services url. Would love an explanation from someone who understands what's happening under the hood

### Added comments
* Details for the workaround can be found here: 
>  https://github.com/knative/serving/blob/b31d96e03bfa1752031d0bc4ae2a3a00744d6cd5/docs/creating-a-kubernetes-cluster.md#loadbalancer-support-in-minikube

* As it points out, you have to run this *everytime* you restart minikube (presumably because there's no reliable way to set a static IP for minikube and it's relying on `$(minikube ip)`)

**Comment by AngusHelm** [comment]
I ran into this issue a couple of days ago and subscribed to this bug, I've since managed to workaround it by running the `minikube tunnel` command in a separate terminal: https://minikube.sigs.k8s.io/docs/tasks/loadbalancer/
I assume it does something very similar to @alechp's fix. If the tunnel's running it allows the `<pending>` status to clear and gives the service a `10.` ip address

**Comment by alechp** [comment]
@AngusHelm Thanks for showing me that. Definitely seems like the intended way.

For some reason the `<pending>` status never goes away for me when I use `minikube tunnel`. Any tips?

### Checking services external IP
![Screen Shot 2020-02-20 at 12 04 29 PM](https://user-images.githubusercontent.com/3058939/74973961-404cb900-53d9-11ea-8bcf-eaec64d4b664.png)

### Tunnel running
![Screen Shot 2020-02-20 at 12 03 36 PM](https://user-images.githubusercontent.com/3058939/74973885-2317ea80-53d9-11ea-9b77-194b6143eb9e.png)

**Comment by alechp** [comment]
### Update, solved my own problem

Because my method was writing to the ip table manually (without any cleanup) I needed to manually delete the route, like so:
```
sudo route -n delete 10.96.0.0
```

After that, minikube tunnel worked like a charm. Thanks again for the tip @AngusHelm
