### ISSUE TITLE
Do we have a flag for enabling ssl-passthrough for a mapping in ambassador CR or annotations ?

### ISSUE THREAD

**Issue by avinashkumar1289** [datawire/ambassador#2601]
I am currently using an ingress.yaml in my application which i am trying to replace with ambassador.But ingress.yaml support ssl-passthrough by this annotation ```nginx.ingress.kubernetes.io/ssl-passthrough: "true"```
I couldn't find anything like this in ambassador documentations .
Is it supported in Ambassador  ?

**Comment by richarddli** [comment]
Yes, you can use a `TCPMapping`. Please do not use GitHub for support and join the Slack.

**Comment by mohania17** [comment]
> I am currently using an ingress.yaml in my application which i am trying to replace with ambassador.But ingress.yaml support ssl-passthrough by this annotation `nginx.ingress.kubernetes.io/ssl-passthrough: "true"` I couldn't find anything like this in ambassador documentations . Is it supported in Ambassador ?

Hi @avinashkumar1289 , did you by any chance got the solution how to use TCP Mapping for ssl-passthrough?

**Comment by cindymullins-dw** [comment]
You can do this with [a TCP mapping](https://www.getambassador.io/docs/emissary/latest/topics/using/tcpmappings#tcpmapping-resources).  For purposes of this discussion you can consider TLS and SSL as equivalents.  Our docs talk about how to [not terminate TLS](https://www.getambassador.io/docs/emissary/latest/topics/using/tcpmappings#tcpmapping-and-tls) with Emissary - those would be the relevant points for allowing SSL-passthrough.  Please also check the notes there about the [Listener and TLS termination](https://www.getambassador.io/docs/emissary/latest/topics/using/tcpmappings#downstream-configuration) because these need to be in agreement to work.
