### ISSUE TITLE
[HTTP 301] Getting results in curl different than browser

### ISSUE THREAD

**Issue by DarkBlaez** [datawire/ambassador#2852]
I have ambassador installed per the instructions on the main site. This is installed in the ambassador namespace. Things seem to work, dashboard comes up , etc.

I deployed a simple httpbin route as follows:

apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  httpbin_mapping
      prefix: /httpbin/
      service: httpbin.org:80
      host_rewrite: httpbin.org
  name: httpbin
spec:
  ports:
    - name: httpbin
      port: 80

When I curl this: curl <ambassador ip 10.25.0.200>/httpbin/ip I end up with the result:*   Trying 10.25.0.200...
* TCP_NODELAY set
* Connected to 10.25.0.200 (10.25.0.200) port 80 (#0)
> GET /httpbin/ip HTTP/1.1
> Host: 10.25.0.200
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< location: https://10.25.0.200/httpbin/ip
< date: Mon, 06 Jul 2020 21:52:56 GMT
< server: envoy
< content-length: 0
<
* Connection #0 to host 10.25.0.200 left intact
* Closing connection 0

When I use a browser it returns the result I expect in json
{
  "origin": "10.42.0.0, X.X.X.X"
}

For the endpoint : https://10.25.0.200/ambassador/v0/check_ready
When viewed in a browser gives the correct result 
ambassador readiness check OK (within the last second)

when curl'd gives the same HTTP 301

Why would I see this http 301 from curl on the same URL? It is doing this for other routes I attempt to create. I did notice that the browser is rolling these to HTTPS and when curl on HTTPS will give an SSL error. Should I not see comparable results. Do I need to pull the certs and pass with curl then to get the response I am hoping? I am not sure why when the examples show http I am seeing the redirect to https in the browser.

Can someone lend some clarity to this for me, I'd greatly appreciate it.

Thanks
DB

**Comment by cakuros** [comment]
Hi DarkBlaez,
By default, Ambassador Edge Stack redirects to TLS as a security measure.  This can be overwritten with a `Host` as described here: https://www.getambassador.io/docs/latest/topics/running/host-crd/#secure-and-insecure-requests.

If you want to be able to route unencrypted http traffic, you have to set `spec.requestPolicy.insecure.action: Route`.

The reason you're seeing the behavior in curl is because curl does not automatically pursue redirects, if you pass the -L flag it should work (I like keeping https://ec.haxx.se/http/http-cheatsheet handy for things like this ;))

**Comment by DarkBlaez** [comment]
Thanks so much, I will make these adjustments and appreciate the links. That helped me a lot. Appreciate it. Thanks again
