### ISSUE TITLE
Ambassador YAML Distribution

### ISSUE THREAD

**Issue by plombardi89** [datawire/ambassador#289]
Determine the best ways to distribute Ambassador

- Better way to manage different Ambassador YAML
- Helm?
- Forge?

**Comment by rhs** [comment]
FWIW, I don't think either one really addresses the problem of targeting different versions/configurations of kubernetes particularly well.

**Comment by plombardi89** [comment]
I don't think its our responsibility to target all configurations in existence. But this would also be why we should document the bare minimum needed to get Ambassador up and running and then people can write their own pod specs or what have you as needed

**Comment by richarddli** [comment]
I don't think we need to target all configurations in existence. But I do think that a huge reason why people use Ambassador is because it works pretty well out of the box, and you don't need to know all about readiness & liveness checks & imagePullPolicy & other stuff for it to work in the base case.
