### ISSUE TITLE
CVE-2021-14343 (PyYAML)

### ISSUE THREAD

**Issue by dfl-erik** [datawire/ambassador#3347]
Vulnerability CVE-2021-14343 shows up against datawire/ambassador:1.12.3 (was also present against 1.12.2) when scanning image with Anchore scanner version 0.9.3.

This vulnerability is fixed in version 5.4 of PyYAML, however because PyYAML is a distutils installed project it is not able to be fixed by upgrading PyYAML using pip3.

Suggested fix: a version of datawire/ambassador with PyYAML v5.4 installed instead of PyYAML-5.3.1.

**Comment by kflynn** [comment]
Hey Erik, thanks for the report! 

Since the beginning, Ambassador has always used the PyYAML `SafeLoader` and _only_ the `SafeLoader`, because of exactly this sort of thing. CVE-2021-14343 is only present in the `FullLoader` class, which we don't use, so Ambassador isn't vulnerable to it. (We actually dug into the source on this one to make sure that we couldn't be somehow bitten through the `SafeLoader` class; all looks safe.)

We're going to go ahead and get to PyYAML 5.4 anyway (tracked in https://github.com/datawire/ambassador/issues/3349), but the CVE itself shouldn't be a problem. Thanks!

**Comment by dfl-erik** [comment]
klfynn,

As always thank you so much for the quick reply and great information.

Thanks,

Erik
