### ISSUE TITLE
Istio + ambassador: conflict envoy

### ISSUE THREAD

**Issue by lluunn** [datawire/ambassador#367]
It's similar to #160, but a little different

Error is the same: unable to bind domain socket with id=0 (see --base-id option)

However
- I am using manual inject for istio instead of auto inject 
- I want both functionality of istio and ambassador: 
  - ambassador for dynamic routing
  - want the ambassador service to be part of the istio service mesh so I can collect telemetry metrics  like [this](https://istio.io/docs/tasks/telemetry/metrics-logs.html). So IIUC, I need the istio injection for ambassador deployment.

Any suggestion?
We are using quay.io/datawire/ambassador:0.30.1.

**Comment by richarddli** [comment]
We don't support injecting the istio sidecar. If you want to collect telemetry, Ambassador exposes metrics (see https://www.getambassador.io/reference/statistics). I'd be interested in your use case where you want Istio style metrics from Ambassador, since in general the edge metrics that Ambassador gives you are probably more applicable. But I'm sure I'm missing something :).

**Comment by richarddli** [comment]
Closing for now.
