### ISSUE TITLE
kubewatch.py dies intermittently

### ISSUE THREAD

**Issue by richarddli** [datawire/ambassador#453]
**Describe the bug**

kubewatch.py dies intermittently

no new ambassador-config folder produced even when services are changed on a given pod (the other ambassador pods still work)

**Versions (please complete the following information):**
 - Ambassador: 0.33.1
 - Kubernetes environment: AZS

cc: @alexhcheng

**Comment by alexhcheng** [comment]
Ambassador: 0.31.0
Env: Azure ACS

we have 3 pods running and 1 pod picked up the change.

We inspect: kubectl exec -it [pod] -- ls -l /etc/ | grep ambassador

and the last updated timestamp for the malfunctioning pods haven't changed (thus route table hasn't been updated)

**Comment by kflynn** [comment]
I handed @alexhcheng a version of Ambassador that has kubewatch log to a file as well as to stdout, so that we have a better chance of seeing what's going on.

**Comment by kflynn** [comment]
I'm going to close this because we found and have addressed quite a few kubewatch issues that, I think, are the root of this problem. Ambassador 0.34.3 (already out) has almost all of these fixes; Ambassador 0.34.4 (probably out tomorrow) picks up the last one.

**Please reopen this issue, or file a new one, if the problem rears its head again.** Thanks!
