### ISSUE TITLE
Users want access to Istio's more complex routing logic

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#64]
Istio is capable of a rich set of routing behaviors that Ambassador should provide access to, for example:

- A/B testing ("Split evenly between these backends")
- Canary deployment ("1% of traffic goes to this new backend -- OK, now 2%. Now 10%...")
- Service A goes to a cluster of 10 hosts. Service B goes to a cluster of 15. However, 5 of the hosts for B are the same as for A...

Much of these can be managed by weighted round-robin, but some will require intelligence in how Ambassador constructs Envoy clusters.

**Comment by kflynn** [comment]
We can handle all three of the above scenarios by letting Ambassador accept multiple weighted services in a map definition. Ambassador should also be able to manage Istio's implementation though.

**Comment by audovychenko** [comment]
We have the same problem on our project trying to integrate Ambassador 0.39 and Istio 1.0.1. The issue is still open from June 2017 and the documentation seems to be hinting about it https://www.getambassador.io/user-guide/with-istio#roadmap:

> There are a number of roadmap items that we'd like to tackle in improving Istio integration. This includes supporting Istio routing rules in Ambassador and full propagation of request headers (e.g., Zipkin tracing) between Ambassador and Istio. 

This issue may be a show-stopper for the usage of Ambassador gateway on our project.
