### ISSUE TITLE
Allow wildcard in CORS "origins"

### ISSUE THREAD

**Issue by lalit-pundir** [datawire/ambassador#788]
As per example for adding CORS on ambassador module we have the following setting :->

--- 
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: development
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Module
      name: ambassador
      ambassador_id: ambassador-development
      config:
        cors:
          origins: http://foo.example.com,http://bar.example.com
          methods: POST, GET, OPTIONS, PUT
          headers: Content-Type
          credentials: true   
spec: 
  ports: 
    - port: 80
  selector: 
    service: ambassador
  type: LoadBalancer

But as per ambassador document wildcard for "origins" does not seem to be feasible at this moment.

We would like to have cors "origins" support wildcard feature such that we can add :->

 

> config:
>         cors:
>           origins: *.example.com,*.restservice.com

So that we don't need to care about allowing all the sub-domain and also whether allowed domain url is working on http or https

**Comment by plombardi89** [comment]
This should already be possible at a very high-level by setting `origin: *`.

The CORS specification does not support sending back wild card origins (e.g. `*.example.org`) so while we _might_ be able to coerce Envoy into sending back wildcard origins it is undefined behavior for a browser adhering to CORS understands how to handle such an origin.

The solution most often employed by other HTTP proxies is to dynamically populate the `Access-Control-Allow-Origin` header when the request is received with the value of the `Origin` header. This should already be possible if you use an Ambassador External Auth Service. Please read: https://www.getambassador.io/reference/cors#authservice-and-cross-origin-resource-sharing

## Reference Material
- https://www.w3.org/TR/cors/ (the complete spec)
- https://www.w3.org/TR/cors/#access-control-allow-origin-response-header (the ACAO header... interestingly the W3C calls out the ACAO as usually only allowing a single value rather than a list ... probably because of browser implementations)

**Comment by lalit-pundir** [comment]
Yes "origin: *" but we would like to have same for sub-domain. So you mean to say that CORS validation should be added on Auth-Service level other than on ambassador?

**Comment by lavoiedn** [comment]
Apparently matching origins based on a regex is [an upcoming feature in envoy 1.8](https://github.com/envoyproxy/envoy/issues/2526), so instead of using "`*.example.com`", it would look something like "`.*\\.example\\.com`", I think?

Looking at the `cors_filter`'s documentation, it would also need to define the new property [allow_origin_regex](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-field-route-corspolicy-allow-origin-regex).

In the meantime, it does seem like implementing it via extauth is the best way to go about it.

**Comment by mderazon** [comment]
> The solution most often employed by other HTTP proxies is to dynamically populate the Access-Control-Allow-Origin header when the request is received with the value of the Origin header. This should already be possible if you use an Ambassador External Auth Service. 

@plombardi89 how would this be possible with an external auth service ?
`Access-Control-Allow-Origin` is a **response** header and the request flows through the ext auth service but the response does not, am I mistaken ?

I can add whatever header I want for the request in the auth service but that won't help as only the upstream api and ambassador will be able to add response headers...

**Comment by ysaakpr** [comment]
@mderazon Yeah....thats right, are there any other way to do it now ?

**Comment by anoopmash** [comment]
Would it be possible to allow wildcard[ Eg: https://*.[foo.com](http://foo.com/)] in orgin?
