### ISSUE TITLE
Where customize timeout_ms parameter in envoy?

### ISSUE THREAD

**Issue by jpfaria** [datawire/ambassador#833]
I'm trying to customize timeout_ms this way:

`---
apiVersion: ambassador/v0
kind:  Mapping
name: service_mapping
prefix: /path/
service: service:80
tls: false
envoy_override:
  timeout_ms: 30000`

and not working.

**Comment by richarddli** [comment]
If you're filing a bug report, please complete the full bug report template.

Otherwise, if you need help, please join our Slack at https://d6e.co/slack.

In regards to your specific issue, `timeout_ms` is a native Ambassador annotation; there's no need to use `envoy_override`. See the documentation: https://www.getambassador.io/reference/mappings#configuring-mappings.
