### ISSUE TITLE
Support removing headers

### ISSUE THREAD

**Issue by klarose** [datawire/ambassador#943]
**Please describe your use case / problem.**
I want to sanitise input to my upstream by removing specific headers from requests. In particular, I am using a header to make a decision at ingress. I do not want my upstream service to see that header, either because I don't want the information leaking, or because it will conflict with something else.

**Describe the solution you'd like**
A good solution would allow me to list the headers I want removed. If the header is not present in the request the request should be treated as though the header were removed.

The solution will look similar to how we [add request headers](https://www.getambassador.io/reference/add_request_headers/), except rather than an object specifying a mapping of header to value, we would have a list of headers to remove.

The solution should be implemented by extending the HTTP route in envoy. See the
[request_headers_to_remove
](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/rds.proto#envoy-api-msg-routeconfiguration) for details.

**Describe alternatives you've considered**
An alternative is to have the client send different headers. However, that does not help when I do not want the information leaking. We could overwrite the header by adding a new header with a fixed value. However, that does not help with the case where the header being present causes problems in the upstream. I may also not have control over the client.

I considered having the list of headers to remove be a mapping similar to how headers are added, with the value being some match criteria such as a regex. However, the envoy documentation implies that the match is an exact match, so I do not think that would work.

**Additional context**
I proposed this feature on the ambassador-dev slack channel.

**Comment by ysaakpr** [comment]
Why there are no update on this ticket..This is one of the very basic requirement to strip down all the sensitive information going upstream. In our case we have api gateway routing requests to external end points and its mandatory to delete the internal secrets in headers going out.  I was done all the setup to use ambassador, and now it looks like a stopper to use ambassador. I may replace the headers in the auth service to some dummy data, but its still not safe because of few places it causing conflicts. 
Are there any specific reason to not support this. Are there support from envoy proxy to do the same ?

**Comment by klarose** [comment]
@ysaakpr I'm fairly certain envoy supports this. I linked to the relevant configuration field in the main issue description: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/rds.proto#envoy-api-msg-routeconfiguration
